name: "Submit an Article"
description: 'Submit an article to the Experimental ("Github") Track at JoVI'
title: "[SUBMISSION] <title>"
labels: [submission]
assignees: mjskay
body:
- type: markdown
  attributes:
    value: >
      > [!IMPORTANT]
      
      > Please read the [Experimental Track submission instructions](https://www.journalovi.org/submit.html#experimental)
      and the [Author Guidelines](https://www.journalovi.org/author-guide.html) before submitting your article.
      

      To submit your paper, fill out this form and submit the issue. Once you have submitted the issue, the JoVI
      Technical Chair for the Experimental Track will bring your paper's repository into the JoVI Github organization
      and contact you with further instructions.
- type: input
  attributes:
    label: Title
    description: >
      Provide the title of your paper.
  validations:
    required: true
- type: input
  attributes:
    label: Source repository URL
    description: >
      Provide the URL of the respository containing your paper (e.g., a Github repository). We will clone this repository into the JoVI organization.
  validations:
    required: true
- type: input
  attributes:
    label: Desired URL stub
    description: >
      Provide a suggested URL stub in the form `20XX-LASTNAME-STUB` to be used for URLs for this paper on the JoVI website. For example, 
      the paper [Gatherplot: A Non-Overlapping Scatterplot](https://www.journalovi.org/2023-park-gatherplots/) by Deokgun Park et al uses
      the stub `2023-park-gatherplots`.
  validations:
    required: true
- type: textarea
  attributes:
    label: Authors
    description: >
      Provide a list of authors, their emails, and their institutions, with one author per line. For example: 

      ```
      
      Joe Bob, joe@bob.com, Bobjoe University      
      
      Jane Smith, jane@smith.com, Smithjane University
      
      ```


      **NOTE:** If you wish to submit your paper anonymously, write "anonymous" in this box. After creating this submission issue, 
      email [submit@journalovi.org](mailto:submit@journalovi.org) with a link to the created issue and a list of your authors.
  validations:
    required: true
- type: textarea
  attributes:
    label: Github IDs
    description: >
      Provide a list of github usernames of all authors who wish to have write access to the paper during revisions, 
      with one username per line.
  validations:
    required: true
- type: textarea
  attributes:
    label: Conflicts
    description: >
      Provide a list of any folks who might review this paper with whom you would have conflicts 
      (we follow the [ACM COI policy](https://www.acm.org/publications/policies/conflict-of-interest)), including:
      
      - JoVI Organizers or Editors (See the [People Page](https://www.journalovi.org/people.html))
      
      - People who might be natural reviewers of your paper but with whom you have a conflict.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Article format
    description: >
      What format and technical setup does your paper require? If it is "Other/Unsure", provide a description below.
    options:
    - 
    - Quarto
    - Idyll
    - RMarkdown
    - Static HTML + JavaScript (e.g. Distill)
    - Shiny
    - Other/Unsure (describe below)
  validations:
    required: true
- type: textarea
  attributes:
    label: Article format details
    description: >
      If you answered "Other/Unsure" above, describe your paper format or required technical setup. If the details are in a file 
      in your repository (such as a README), you may also refer to that file.
- type: checkboxes
  attributes:
    label: Github Pages setup
    description: >
      Experimental track papers are served as HTML from [journalovi.org](https://www.journalovi.org/) using [Github Pages](https://pages.github.com/).
      Use this box to indicated if you have already set up Github Pages on your submitted repository.


      **If you are experienced using Github Pages**, we recommend setting up Github Pages rendering on your own repository prior to submitting
      your paper. This will make it easier for the Tech Chair to adapt your paper to work with our setup. The most important aspect of the
      setup is that you have a Github action that renders your paper when the source it changes. Some examples:


      - [A workflow for Quarto papers](https://github.com/journalovi/jovi-template-quarto/blob/main/.github/workflows/publish.yml). This is used
      by the JoVI Quarto template.

      - [A workflow for Idyll papers](https://github.com/journalovi/2024-Cashman-PAC-learning-game/blob/master/.github/workflows/publish.yml). 
      
      - [A workflow for a custom rendering pipeline](https://github.com/journalovi/2024-luong-graphical-models/blob/main/.github/workflows/publish.yml).
      This is was adapted from the Idyll workflow by changing the lines that run `node` and `npm` and ensuring the last step copies the
      correct output folder to the `gh-pages` branch.
      
      - For static HTML + JavaScript, a rendering workflow is not required, simply write your paper in `index.html` in the root folder of the repository.


      **If you are not experienced using Github Pages**, it is not required for you to set it up prior to submitting (though it will make 
      processing your submission faster). Leave this checkbox blank and the Tech Chair will assist you.      
    options:
    - label: I have set up Github Pages
- type: checkboxes
  attributes:
    label: Technical checklist
    description: >
      These checks help ensure that your rendered article contains the required information. If you are unsure
      of any of these checkboxes, leave them blank. Then, after creating this issue, reply with a comment explaining what 
      you are unsure about. The Tech Chair will reply and help get your submission set up.


      In particular, we require the `<title></title>` tag of the rendered article contains the title of the paper as this
      is used in some of our paper listing scripts.


      We also require an infobox to be placed at the top of the paper indicating the paper is under review at JoVI.


      In Quarto this looks like:
      
      
      ```
      
      ::: {.callout-important appearance="simple"}
      
      ## Under Review {.unnumbered}
      
      This paper is [under review](https://www.journalovi.org/under-review.html) on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/). See the [reviewing process](https://github.com/journalovi/20xx-repo-name/issues).
      
      :::
      
      ```
      
      
      In HTML this could be:
      
      ```
      
      <p><strong>Under Review:</strong> This paper is <a href="https://www.journalovi.org/under-review.html">under review</a> on the experimental track of the <a href="https://www.journalovi.org/">Journal of Visualization and Interaction</a>. See the <a href="https://github.com/journalovi/20xx-repo-name/issues">reviewing process</a>.</p>
      
      ```
    options:
    - label: The `<title>` tag of my page contains the title of my article
    - label: The article contains an infobox indicating it is under review at JoVI
  validations:
    required: true
